# Generated by Django 4.0 on 2022-01-19 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtocart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='addtocart',
            name='user',
        ),
    ]
