# Generated by Django 4.0 on 2022-01-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtocart',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='addtocart',
            name='shippingPrice',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
