# Generated by Django 4.0 on 2022-01-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_alter_addtocart_price_alter_addtocart_shippingprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtocart',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
    ]
