# Generated by Django 4.0 on 2022-01-25 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carts', '0003_addtocart_is_ordered'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carts.addtocart')),
            ],
        ),
    ]
