# Generated by Django 4.0 on 2022-01-25 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_oders_address_oders_city_oders_postalcode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oders',
            name='cart',
        ),
    ]
