# Generated by Django 4.0 on 2022-01-16 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('products', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='take_categoryname', to='products.categoryname'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_sub_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='take_sub_categoryname', to='products.categorysubname'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='take_username', to='auth.user'),
        ),
    ]
