# Generated by Django 4.0 on 2022-01-16 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_category_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryname',
            old_name='Category_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='categorysubname',
            old_name='Category_sub_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='product',
            name='category_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks1', to='products.categoryname'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_sub_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks2', to='products.categorysubname'),
        ),
    ]
