# Generated by Django 4.0 on 2022-01-20 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_category_remove_product_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
